// <auto-generated />
using System;
using Hotel_Reservation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel_Reservation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240910084433_changeRoomName")]
    partial class changeRoomName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hotel_Reservation.Models.MealPlan", b =>
                {
                    b.Property<int>("MealPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealPlanId"));

                    b.Property<string>("MealPlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MealPlanId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("Hotel_Reservation.Models.MealPlanPerSeason", b =>
                {
                    b.Property<int>("MealPlanID")
                        .HasColumnType("int");

                    b.Property<int>("MealSeasonStartAndEndID")
                        .HasColumnType("int");

                    b.Property<decimal>("RatePerPerson")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MealPlanID", "MealSeasonStartAndEndID");

                    b.HasIndex("MealSeasonStartAndEndID");

                    b.ToTable("MealPlanPerSeasons");
                });

            modelBuilder.Entity("Hotel_Reservation.Models.MealSeasonStartAndEnd", b =>
                {
                    b.Property<int>("MealSeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealSeasonId"));

                    b.Property<DateTime>("SeasonEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SeasonStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MealSeasonId");

                    b.ToTable("MealSeasonStartAndEndSeasons");
                });

            modelBuilder.Entity("Hotel_Reservation.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MealPlanID")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfAdult")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("int");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("MealPlanID");

                    b.HasIndex("RoomID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Hotel_Reservation.Models.RoomSeason", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RoomSeasonStartAndEndID")
                        .HasColumnType("int");

                    b.Property<decimal>("RatePerRoom")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RoomTypeId", "RoomSeasonStartAndEndID");

                    b.HasIndex("RoomSeasonStartAndEndID");

                    b.ToTable("RoomSeasons");
                });

            modelBuilder.Entity("Hotel_Reservation.Models.RoomSeasonStartAndEnd", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonId"));

                    b.Property<DateTime>("SeasonEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SeasonStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SeasonId");

                    b.ToTable("RoomSeasonStartAndEnds");
                });

            modelBuilder.Entity("Hotel_Reservation.Models.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeId"));

                    b.Property<string>("RoomTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomTypeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Hotel_Reservation.Models.MealPlanPerSeason", b =>
                {
                    b.HasOne("Hotel_Reservation.Models.MealPlan", "MealPlan")
                        .WithMany("MealPlanPerSeason")
                        .HasForeignKey("MealPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_Reservation.Models.MealSeasonStartAndEnd", "MealSeasonStartAndEnd")
                        .WithMany("MealPlanPerSeason")
                        .HasForeignKey("MealSeasonStartAndEndID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");

                    b.Navigation("MealSeasonStartAndEnd");
                });

            modelBuilder.Entity("Hotel_Reservation.Models.Reservation", b =>
                {
                    b.HasOne("Hotel_Reservation.Models.MealPlan", "MealPlan")
                        .WithMany("Reservations")
                        .HasForeignKey("MealPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_Reservation.Models.RoomType", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Hotel_Reservation.Models.RoomSeason", b =>
                {
                    b.HasOne("Hotel_Reservation.Models.RoomSeasonStartAndEnd", "RoomSeasonStartAndEnds")
                        .WithMany("RoomSeasons")
                        .HasForeignKey("RoomSeasonStartAndEndID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_Reservation.Models.RoomType", "Rooms")
                        .WithMany("RoomSeasons")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomSeasonStartAndEnds");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Hotel_Reservation.Models.MealPlan", b =>
                {
                    b.Navigation("MealPlanPerSeason");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Hotel_Reservation.Models.MealSeasonStartAndEnd", b =>
                {
                    b.Navigation("MealPlanPerSeason");
                });

            modelBuilder.Entity("Hotel_Reservation.Models.RoomSeasonStartAndEnd", b =>
                {
                    b.Navigation("RoomSeasons");
                });

            modelBuilder.Entity("Hotel_Reservation.Models.RoomType", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("RoomSeasons");
                });
#pragma warning restore 612, 618
        }
    }
}
